networks:
  frontend:
  backend:

services:
  searx:
    container_name: searx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SEARX_GID=977
        - SEARX_UID=977
        - TIMESTAMP_SETTINGS=0
        - TIMESTAMP_UWSGI=0
        - VERSION_GITCOMMIT=unknown
        - LABEL_DATE=
        - GIT_URL=unknown
        - SEARX_GIT_VERSION=unknown
        - LABEL_VCS_REF=
        - LABEL_VCS_URL=
      labels:
        maintainer: "searx <${GIT_URL}>"
        description: "A privacy-respecting, hackable metasearch engine."
        version: "${SEARX_GIT_VERSION}" 
        org.label-schema.schema-version: "1.0" 
        org.label-schema.name: "searx" 
        org.label-schema.version: "${SEARX_GIT_VERSION}" 
        org.label-schema.url: "${LABEL_VCS_URL}" 
        org.label-schema.vcs-ref: ${LABEL_VCS_REF} 
        org.label-schema.vcs-url: ${LABEL_VCS_URL} 
        org.label-schema.build-date: "${LABEL_DATE}" 
        org.label-schema.usage: "https://github.com/searx/searx-docker" 
        org.opencontainers.image.title: "searx" 
        org.opencontainers.image.version: "${SEARX_GIT_VERSION}" 
        org.opencontainers.image.url: "${LABEL_VCS_URL}" 
        org.opencontainers.image.revision: ${LABEL_VCS_REF} 
        org.opencontainers.image.source: ${LABEL_VCS_URL} 
        org.opencontainers.image.created: "${LABEL_DATE}" 
        org.opencontainers.image.documentation: "https://github.com/searx/searx-docker"
    restart: always
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/etc/searx
      - ./logs:/var/log/uwsgi

volumes:
  database_data:

secrets:
